app:
  instance:
    code: bv-public
    profile: dev
  error:
    prefix: hmis
  authority:
    # 设置为true时，项目启动会覆盖redis内容(authority.json)，设置为false，只要redis有就不覆盖，默认为true
    clear-config: true
    # 设置为true时，项目启动会覆盖redis角色权限，默认为false
    clear-role-permissions: true
    # 是否校验url权限
    check-url: true
  redis:
    prefix: hmis
  file:
    uploadPath: ./file/upload
    template-path: classpath:template
    exportPath: ./file/export
server:
  port: 8080
  tomcat:
    max-threads: 500
logging:
  config: classpath:logback-config.xml
  file: ${app.instance.code}
  path: ./log
  level:
    root: info
    com.bestvike: debug
    org.springframework.security: warn
spring:
  application:
    name: ${app.instance.code}-${app.instance.profile}
  http:
    converters:
      preferred-json-mapper: fastjson # json 转换器, 接收数据和请求数据时使用
      preferred-xml-mapper: jackson # xml 转换器, 请求数据时使用
    encoding:
      force: true
  servlet:
    multipart:
      max-file-size: 20MB # 最大文件大小
      max-request-size: 20MB # 最大请求大小
  redis:
    host: 10.10.12.1
    port: 6379
    timeout: 10s
    lettuce:
      pool:
        min-idle: 10
        max-idle: 20
        max-active: 100
  data:
    mongodb:
      uri: mongodb://bvdf:123456@127.0.0.1:27017/bvdfMongo
datasources:
  center:
    #jdbc-url: jdbc:mariadb://192.168.2.21:3306/hmis
    jdbc-url: jdbc:oracle:thin:@127.0.0.1:1521/orcl
    driver-class-name: oracle.jdbc.driver.OracleDriver
    username: datasource_xjws
    password: datasource_xjws
    hikari:
      minimum-idle: 2
      maximum-pool-size: 5
      connection-test-query: select 1
  bvrfis:
    jdbc-url: jdbc:oracle:thin:@127.0.0.1:1521/orcl
    driver-class-name: oracle.jdbc.driver.OracleDriver
    username: bvrfis_xjws
    password: bvrfis_xjws
    hikari:
      minimum-idle: 2
      maximum-pool-size: 5
      connection-test-query: select 1
esConfig:
  # es数据库房屋的索引
  index: house_index
  # es数据库房屋的映射
  type: house_type
  # es集群的名称
  esClusterName: docker-cluster
  # es的IP
  esIP: 192.168.12.129
  # es的port
  esPort: 9300
  # es数据库公司的索引
  corpindex: corp_index
  # es数据库公司的映射
  corptype: corp_type
  # es数据库小区的索引
  regionindex: region_index
  # es数据库小区的映射
  regiontype: region_type



standplatConfig:
  # 是否启用完全匹配 Y启用，N不启用
  isAllMatchEnable: Y
  # 疑似匹配的条数
  unCertainSize: 5
  unCertain:
    # 疑似匹配展示的条数
    showNum: 3
  bvdfToEsSchedule:
    # 是否启用bvdfToEs定时任务 Y启用，N不启用
    isEnable: N
    # 定时时间 每隔5分钟执行一次
    cornTime: 0 0/5 * * * ?
    # 房屋信息表(arc_houseinfo)最大查询条数,防止内存溢出
    houseMaxNum: 20000
    # 批量新增、修改bvdf表的数量
    bvdfBatchNum: 1
  corpToEsSchedule:
    # 定时时间 每隔5分钟执行一次,cornTime为“-”是停止定时
    cronTime: 0/5 * * * * ?

